apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo-prod
nameSuffix: -prod
resources:
#  - ../../bases/backend
  - ../../bases/frontend
#  - ../../bases/cache
  - namespace.yaml
  - ingress.yaml
  - feature-flags.yaml
  - ui-config.yaml
transformers:
  - labels.yaml
patches:
#  - path: feature-flag-env.yaml
  - path: frontend-replicas.yaml
