apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: add-prod-suffix
suffix: -prod
fieldSpecs:
  - path: metadata/name
    kind: Deployment
  - path: metadata/name
    kind: HorizontalPodAutoscaler
  - path: spec/scaleTargetRef/name
    kind: HorizontalPodAutoscaler
