apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo-preq
nameSuffix: -preq
resources:
#  - ../../bases/backend
  - ../../bases/frontend
#  - ../../bases/cache
  - ingress.yaml
  - namespace.yaml
  - ui-config.yaml
transformers:
  - labels.yaml
