apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: preq
resources:
  - ../../bases/backend
  - ../../bases/frontend
  - ../../bases/cache
  - namespace.yaml
  - ui-config.yaml
transformers:
  - labels.yaml
