apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: add-preq-suffix
suffix: -preq
fieldSpecs:
  - path: metadata/name
    kind: Deployment
  - path: metadata/name
    kind: HorizontalPodAutoscaler
  - path: spec/scaleTargetRef/name
    kind: HorizontalPodAutoscaler
