apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo-dev
nameSuffix: -dev
resources:
#  - ../../bases/backend
  - ../../bases/frontend
#  - ../../bases/cache
  - namespace.yaml
  - ingress.yaml
  - feature-flags.yaml
  - ui-config.yaml
transformers:
  - labels.yaml
#patches:
#  - path: feature-flag-env.yaml
