apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo-ui-config
  labels:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: ui-config
data:
  message: "Podinfo running in the production overlay"
