apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: add-qa-suffix
suffix: -qa
fieldSpecs:
  - path: metadata/name
    kind: Deployment
  - path: metadata/name
    kind: HorizontalPodAutoscaler
  - path: spec/scaleTargetRef/name
    kind: HorizontalPodAutoscaler
